config/routes.rb
Photogenic::Application.routes.draw do
  resources :contents, only: ['new', 'create', 'show']

  get '/item/:id(.:format)', to: 'contents#show'

  root to: 'contents#new'
end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessor :body

  validate :check_presence
  validate :check_content_type
  validate :check_file_size

  has_attached_file :body, {
    path: ":rails_root/public/raw/:id_sha1.:extension",
    url:  "#{ActionController::Base.relative_url_root}/raw/:id_sha1.:extension"
  }

  def check_presence
    unless self.body_file_name
      errors.add(:content, "ファイルを指定してください")
    end
  end

  def check_content_type
    if !['image/jpeg', 'image/gif','image/png'].include?(self.body_content_type)
      errors.add(:content_type, "'jpeg', 'gif', 'png' 以外のファイルはアップロード出来ません")
    end
  end

  def check_file_size
    if self.body_file_size > 1024 * 1024 * 5
      errors.add(:content_size, "5MBを超えるファイルはアップロード出来ません")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:edit, :update]

  # GET /contents/1
  # GET /contents/1.json
  def show
    begin
      @content = Content.where(["name = ?", params[:id]]).first!
      @content.last_accessed_at = Time.now
      @content.save # Error handling はそこまで重要ではないので省略. 後で必要になったら考える

      respond_to do |format|
        format.html
      end
    rescue
      # 404
    end
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # POST /contents
  # POST /contents.json
  def create
    begin
      @content = Content.new(content_params)
    rescue
      # パラメータ足りない (ファイル指定されてない) 場合の処理
      respond_to do |format|
        format.html { redirect_to :root, :flash => {:error => "ファイルを指定して下さい"} }
      end
      return
    end

    @content.last_accessed_at = @content.body_updated_at

    (@content.name, @content.extension) = @content.body.path.split('/')[-1].split('.')

    respond_to do |format|
      if @content.save
        format.html { redirect_to "/item/#{@content.name}", id: @content.name }
        format.json { render action: 'show', status: :created, location: @content }
      else
        format.html { render action: 'new' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(:name, :category, :mime, :last_accessed_at, :created_at, :updated_at, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<section id="tutorialArea">
	<%= image_tag 'title.png', :id=>"t_title" %>
	<%= image_tag 'takeapicture.png', :id=>"t_take" %>
	<%= image_tag 'uploade.png', :id=>"t_upload" %>
	<%= image_tag 'finishing.png', :id=>"t_finishing" %>
	<%= image_tag 'winner.png', :id=>"t_winner" %>
	<%= image_tag 'lose.png', :id=>"t_lose" %>
</section><!-- /#tutorialArea -->
<section id="spTutorialArea">
	<%= image_tag 'tutorial.png' %>
</section>

<section id="uploadArea">
  <%= form_for @content do |f| %>

<div class="body">
      <%= f.file_field :body, :id=>'uploadFile' %>
    </div>
	    <% if flash[:error] %>
	    <div id="noselect"><%= flash[:error] %></div><!-- /#noselect -->
		<% end %>

    <% if @content.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @content.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit :value=>'選択した写真を追加する', :id=>'uploadSubmit' %>
    </div>
  <% end %>
</section><!-- /#uploadArea -->

app/views/contents/show.html.erb
<div class="image">
  <%= image_tag @content.body %>
</div>

<div id="sns">
	<p id="info">SNSで共有して、みんなに見てもらおう！</p>
	<div id="snsButton">
		<div id="twitter">
			<a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja">ツイート</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
		</div><!-- /#twitter -->
	</div><!-- /#snsButton -->
	<div id="back" class="clearFix">
		<%= link_to "TOPに戻る", :action=>"new" %>
	</div><!-- /#back -->
</div><!-- /#sns -->
<!--
    localの状態でfacebookのdata-hrefを%%current_uri%%にすると消えるのでとりあえず仮のurl入れてます
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogenic</title>
  <meta name="viewport" content="width=device-width initial-scale=1.0" />
  <%= favicon_link_tag 'appicon.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="footbottomWrap">
	<header>
		<h1 id="logo"><%= link_to image_tag('logo.png') ,action: "new" %></h1>
	</header>
	<div id="wrapper">
		<article id="contentArea">
	<%= yield %>
		</article><!-- /#contentArea -->
	</div><!-- /#wrapper -->
	<footer id="footer">
		<p id="copy">Copyright &copy; 2013 photogenic All Rights Reserved.</p>
	</footer>
</div><!-- /#footbottomWrap -->
</body>
</html>